version: "3.9"
services:
  app:
    platform: "linux/amd64"
    container_name: biso-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    environment:
    - 'HOSTNAME=0.0.0.0'
    - APPWRITE_API_KEY=${APPWRITE_API_KEY}
    - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
