name: Cleanup PR Preview
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove preview
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/apps/pr-previews/pr-${{ github.event.pull_request.number }}
            docker-compose -f docker-compose.pr-${{ github.event.pull_request.number }}.yml down
            rm -rf /root/apps/pr-previews/pr-${{ github.event.pull_request.number }}