name: Manual PR Preview
on: 
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/apps/pr-previews/pr-${{ inputs.pr_number }}"
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /root/apps/pr-previews/pr-${{ inputs.pr_number }}
            cd /root/apps/pr-previews/pr-${{ inputs.pr_number }}
            ../generate-compose.sh ${{ inputs.pr_number }}
            docker compose -f docker-compose.pr-${{ inputs.pr_number }}.yml up -d --build