name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/apps/pr-previews/pr-${{ github.event.pull_request.number }}"
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/apps/pr-previews/pr-${{ github.event.pull_request.number }}
            ./generate-compose.sh ${{ github.event.pull_request.number }}
            docker-compose -f docker-compose.pr-${{ github.event.pull_request.number }}.yml up -d --build
            
      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `Preview deployed at: pr-${context.issue.number}.yourdomain.com`
            })