name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
      NEXT_PUBLIC_APPWRITE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_APPWRITE_ENDPOINT }}
      NEXT_PUBLIC_APPWRITE_PROJECT: ${{ secrets.NEXT_PUBLIC_APPWRITE_PROJECT }}
      SECRET_ENV_VARIABLE: ${{ secrets.SECRET_ENV_VARIABLE }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb', '**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version

      - name: Install and Build
        run: |
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          if [ -f bun.lockb ]; then
            bun install && bun run build;
          else
            echo "No supported lockfile found!" && exit 1;
          fi

      - name: Verify .next folder contents
        run: |
          if [ ! -d ".next" ] || [ -z "$(ls -A .next)" ]; then
            echo "Error: .next folder is missing or empty after build."
            exit 1
          fi
          ls -lah .next

      - name: Copy Build Artifacts to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".next"
          target: "/root/apps/pr-previews/pr-${{ github.event.pull_request.number }}/.next"

      - name: Verify .next on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/root/apps/pr-previews/pr-${{ github.event.pull_request.number }}/.next" ] || [ -z "$(ls -A /root/apps/pr-previews/pr-${{ github.event.pull_request.number }}/.next)" ]; then
              echo "Error: .next folder is missing or empty on server."
              exit 1
            fi
            ls -lah /root/apps/pr-previews/pr-${{ github.event.pull_request.number }}/.next

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export APPWRITE_API_KEY=$APPWRITE_API_KEY
            export NEXT_PUBLIC_APPWRITE_ENDPOINT=$NEXT_PUBLIC_APPWRITE_ENDPOINT
            export NEXT_PUBLIC_APPWRITE_PROJECT=$NEXT_PUBLIC_APPWRITE_PROJECT
            export SECRET_ENV_VARIABLE=$SECRET_ENV_VARIABLE
            cd /root/apps/pr-previews
            ./generate-compose.sh ${{ github.event.pull_request.number }}
            docker compose -f docker-compose.pr-${{ github.event.pull_request.number }}.yml up -d

      - name: Cleanup Temp Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf /tmp/exc1-biso-*

      - name: Comment PR with Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `Preview deployed at: https://pr-${context.issue.number}.app.biso.no`
            })
